### ISSUE TITLE
Double quotes as value

### ISSUE THREAD

**Issue by gedeminas** [Jeradin/acf-dynamic-table-field#2]
When entering double quote (") in table field and, the table corrupts after saving and doesn't show any values at all.
Although when exporting data to save (JSON.stringify(exportData()) / jquery.editttable.js line 216), double quotes are escaped by stringify function, ACF removes backslashes when saving to db.
Maybe you will thing of something better, but my quickfix was to convert double quotes in exportData() like this: value = value.replace(/"/g, "&quot;");

P.S. I've been using ACF v4

**Comment by Jeradin** [comment]
Delayed reply! I think this is fixed. Again sorry for not getting to this sooner.
